# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: task-management-app-backend:latest
        imagePullPolicy: IfNotPresent # Tells K8s to use the local Minikube image
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        # Note:  add MongoDB connection  via ConfigMaps/Secrets!
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret       # Name of the Secret we just created
              key: MONGO_URI 