# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: task-management-app-backend:latest
        imagePullPolicy: IfNotPresent # Tells K8s to use the local Minikube image
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        # Note: We will add MongoDB connection in Phase 3 via ConfigMaps/Secrets!