# k8s/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: task-management-app-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://localhost:5000/api/tasks" # Points to the K8s backend service!