# k8s/mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData: # 'stringData' lets you write plain text, K8s will automatically Base64 encode it!
  MONGO_URI: "mongodb+srv://<your_username>:<your_password>@cluster0.xxxxx.mongodb.net/taskDB?retryWrites=true&w=majority"
  # 👆 REPLACE THIS with your actual MongoDB Atlas connection string!
  # If you are using the local Minikube MongoDB from docker-compose, use:
  # MONGO_URI: "mongodb://admin:password123@mongodb-service:27017/taskDB?authSource=admin"