# k8s/mongo-db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: supersecretpassword123